import { HumanMessage } from "@langchain/core/messages";
import { StateSchema, MessagesValue, ReducedValue, StateGraph, START, END } from "@langchain/langgraph";
import type { GraphNode } from "@langchain/langgraph";
import { geminiModel, groqModel, mistralModel } from "./models.service.js";
import { z } from "zod";

/**
 * State Schema defines the structure of the state that will be passed through the graph. It includes:
 * - messages: An array of messages, where each message is an instance of HumanMessage.
 * - solution_1: A string that will hold the solution generated by the first model (Mistral).
 * - solution_2: A string that will hold the solution generated by the second model (Gemini).
 * - judge: An object that will hold the scores for both solutions and determine the winner.
 */

const State = new StateSchema({
    messages: MessagesValue,
    solution_1: new ReducedValue(z.string().default(""), {
        reducer: (current, next) => next ?? current,
    }),
    solution_2: new ReducedValue(z.string().default(""), {
        reducer: (current, next) => next ?? current,
    }),
    judge: new ReducedValue(
        z.object({
            solution_1_score: z.number().default(0),
            solution_1_reasoning: z.string().default(""),
            solution_2_score: z.number().default(0),
            solution_2_reasoning: z.string().default(""),
            winner: z.enum(["solution_1", "solution_2"]).default("solution_1"),
        }),
        {
            reducer: (current, next) => next ?? current,
        }
    )
});

/**
 * Solution Node is responsible for generating solutions from both Mistral and Gemini models based on the input message. 
 * It takes the first message from the state, invokes both models in parallel, and updates the state with the generated solutions.
 */

const solutionNode: GraphNode<typeof State> = async (state) => {
    const message = state.messages[0];
    if (!message) throw new Error("No message found in state");

    const [mistral_solution, gemini_solution] = await Promise.all([
        mistralModel.invoke([message]),
        geminiModel.invoke([message]),
    ]);

    return {
        solution_1: mistral_solution.content as string,
        solution_2: gemini_solution.content as string,
    };
};



const judgeNode: GraphNode<typeof State> = async (state) => {
    const { solution_1, solution_2, messages } = state;
    const problem = messages[0]?.content as string;

    const judgeResponse = await groqModel.invoke([
        new HumanMessage(`
            You are a judge evaluating two AI solutions.
            
            Problem: ${problem}
            Solution 1: ${solution_1}
            Solution 2: ${solution_2}
            
            Respond ONLY with a valid JSON object, no extra text, no markdown:
            {
                "solution_1_score": <number 0-10>,
                "solution_1_reasoning": <string>,
                "solution_2_score": <number 0-10>,
                "solution_2_reasoning": <string>
            }
        `)
    ]);

    const parsed = JSON.parse(judgeResponse.content as string);

    return {
        judge: {
            solution_1_score: parsed.solution_1_score,
            solution_1_reasoning: parsed.solution_1_reasoning,
            solution_2_score: parsed.solution_2_score,
            solution_2_reasoning: parsed.solution_2_reasoning,
            winner: parsed.solution_1_score >= parsed.solution_2_score
                ? "solution_1" as const
                : "solution_2" as const,
        },
    };
};

const graph = new StateGraph(State)
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile();

export default async function runGraph(question: string) {
    const result = await graph.invoke({
        messages: [new HumanMessage(question)],
    });

    return {
        solution_1: result.solution_1,
        solution_2: result.solution_2,
        judge: result.judge,
    };
}