import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { StateSchema, MessagesValue, ReducedValue, StateGraph, START, END } from "@langchain/langgraph";
import type { GraphNode } from "@langchain/langgraph";
import { geminiModel, groqModel, mistralModel } from "./models.service.js";
import { z } from "zod";

const FORMATTING_INSTRUCTION = `
Regardless of the user's query, always format your response using professional, high-fidelity markdown.
1. Use hierarchical headers (e.g., ### Section, #### Subsection).
2. Use bolding (**Text**) for key concepts and technical terms.
3. Use consistent lists (numbered or bulleted) for steps or features.
4. Ensure double line breaks between paragraphs for optimal spacing.
5. Use code blocks (\`\`\`language) for any technical data, commands, or math.
Maintain a technical, "Kinetic Observatory" tone—precise, analytical, and data-driven.
`;

/**
 * State Schema defines the structure of the state that will be passed through the graph. It includes:
 * - messages: An array of messages, where each message is an instance of HumanMessage.
 * - solution_1: A string that will hold the solution generated by the first model (Mistral).
 * - solution_2: A string that will hold the solution generated by the second model (Gemini).
 * - judge: An object that will hold the scores for both solutions and determine the winner.
 */

const State = new StateSchema({
    messages: MessagesValue,
    solution_1: new ReducedValue(z.string().default(""), {
        reducer: (current, next) => next ?? current,
    }),
    solution_1_metrics: new ReducedValue(
        z.object({
            latency_ms: z.number().default(0),
            prompt_tokens: z.number().default(0),
            completion_tokens: z.number().default(0),
            total_tokens: z.number().default(0),
        }).default({
            latency_ms: 0,
            prompt_tokens: 0,
            completion_tokens: 0,
            total_tokens: 0,
        }),
        { reducer: (current, next) => next ?? current }
    ),
    solution_2: new ReducedValue(z.string().default(""), {
        reducer: (current, next) => next ?? current,
    }),
    solution_2_metrics: new ReducedValue(
        z.object({
            latency_ms: z.number().default(0),
            prompt_tokens: z.number().default(0),
            completion_tokens: z.number().default(0),
            total_tokens: z.number().default(0),
        }).default({
            latency_ms: 0,
            prompt_tokens: 0,
            completion_tokens: 0,
            total_tokens: 0,
        }),
        { reducer: (current, next) => next ?? current }
    ),
    judge: new ReducedValue(
        z.object({
            solution_1_score: z.number().default(0),
            solution_1_reasoning: z.string().default(""),
            solution_2_score: z.number().default(0),
            solution_2_reasoning: z.string().default(""),
            winner: z.enum(["solution_1", "solution_2"]).default("solution_1"),
        }),
        {
            reducer: (current, next) => next ?? current,
        }
    )
});

/**
 * Solution Node is responsible for generating solutions from both Mistral and Gemini models based on the input message. 
 * It takes the first message from the state, invokes both models in parallel, and updates the state with the generated solutions.
 */

const solutionNode: GraphNode<typeof State> = async (state) => {
    const message = state.messages[0];
    if (!message) throw new Error("No message found in state");

    const systemMsg = new SystemMessage(FORMATTING_INSTRUCTION);

    const start1 = performance.now();
    const mistral_solution = await mistralModel.invoke([systemMsg, message]);
    const end1 = performance.now();

    const start2 = performance.now();
    const gemini_solution = await geminiModel.invoke([systemMsg, message]);
    const end2 = performance.now();

    // Standardized usage extraction in modern LangChain
    const m1_usage = (mistral_solution as any).usage_metadata || (mistral_solution.response_metadata as any).tokenUsage || {};
    const m2_usage = (gemini_solution as any).usage_metadata || (gemini_solution.response_metadata as any).usage || {};

    return {
        solution_1: mistral_solution.content as string,
        solution_1_metrics: {
            latency_ms: Math.round(end1 - start1),
            prompt_tokens: m1_usage.input_tokens || m1_usage.promptTokens || 0,
            completion_tokens: m1_usage.output_tokens || m1_usage.completionTokens || 0,
            total_tokens: m1_usage.total_tokens || m1_usage.totalTokens || 0,
        },
        solution_2: gemini_solution.content as string,
        solution_2_metrics: {
            latency_ms: Math.round(end2 - start2),
            prompt_tokens: m2_usage.input_tokens || m2_usage.prompt_token_count || 0,
            completion_tokens: m2_usage.output_tokens || m2_usage.candidates_token_count || 0,
            total_tokens: m2_usage.total_tokens || m2_usage.total_token_count || 0,
        },
    };
};



const judgeNode: GraphNode<typeof State> = async (state) => {
    const { solution_1, solution_2, messages } = state;
    const problem = messages[0]?.content as string;

    const judgeResponse = await groqModel.invoke([
        new HumanMessage(`
            You are a judge evaluating two AI solutions.
            
            Problem: ${problem}
            Solution 1: ${solution_1}
            Solution 2: ${solution_2}
            
            Respond ONLY with a valid JSON object, no extra text, no markdown:
            {
                "solution_1_score": <number 0-10>,
                "solution_1_reasoning": <string>,
                "solution_2_score": <number 0-10>,
                "solution_2_reasoning": <string>
            }
        `)
    ]);

    const parsed = JSON.parse(judgeResponse.content as string);

    return {
        judge: {
            solution_1_score: parsed.solution_1_score,
            solution_1_reasoning: parsed.solution_1_reasoning,
            solution_2_score: parsed.solution_2_score,
            solution_2_reasoning: parsed.solution_2_reasoning,
            winner: parsed.solution_1_score >= parsed.solution_2_score
                ? "solution_1" as const
                : "solution_2" as const,
        },
    };
};

const graph = new StateGraph(State)
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile();

export default async function runGraph(question: string) {
    const result = await graph.invoke({
        messages: [new HumanMessage(question)],
    });

    return {
        solution_1: result.solution_1,
        solution_1_metrics: result.solution_1_metrics,
        solution_2: result.solution_2,
        solution_2_metrics: result.solution_2_metrics,
        judge: result.judge,
    };
}